# Generated by Django 4.2.5 on 2023-09-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('created_by', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(choices=[('サポート内容', 'サポート内容'), ('オプション', 'オプション'), ('提携司法書士', '提携司法書士'), ('運営者', '運営者'), ('その他', 'その他')], max_length=20, verbose_name='件名')),
                ('content', models.TextField(max_length=300, verbose_name='内容')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_inquiry_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終回答者')),
            ],
            options={
                'verbose_name': '一般お問い合わせ',
                'verbose_name_plural': '一般お問い合わせ',
            },
        ),
    ]
