# Generated by Django 4.2.5 on 2023-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0004_alter_openinquiry_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_half_parent',
            field=models.BooleanField(default=False, verbose_name='異父母'),
        ),
        migrations.AddField(
            model_name='relation',
            name='is_step_child',
            field=models.BooleanField(default=False, verbose_name='連れ子'),
        ),
    ]
