# Generated by Django 4.2.5 on 2023-09-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toukiApp', '0006_ascendant_collateral_decedent_descendant_spouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascendant',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='子'),
        ),
        migrations.AlterField(
            model_name='ascendant',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='子id'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='content_type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral1', to='contenttypes.contenttype', verbose_name='親1'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='content_type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral2', to='contenttypes.contenttype', verbose_name='親2'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='object_id1',
            field=models.PositiveIntegerField(verbose_name='親1id'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='object_id2',
            field=models.PositiveIntegerField(verbose_name='親2id'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='content_type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant1', to='contenttypes.contenttype', verbose_name='親1'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='content_type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant2', to='contenttypes.contenttype', verbose_name='親2'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='object_id1',
            field=models.PositiveIntegerField(verbose_name='親1id'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='object_id2',
            field=models.PositiveIntegerField(verbose_name='親2id'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='配偶者'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='配偶者id'),
        ),
    ]
