# Generated by Django 4.2.5 on 2023-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0007_alter_ascendant_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descendant',
            name='exist',
            field=models.BooleanField(default=False, verbose_name='死亡時存在'),
        ),
    ]
