# Generated by Django 4.2.5 on 2023-09-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0008_alter_descendant_exist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descendant',
            old_name='exist',
            new_name='is_exist',
        ),
    ]
