# Generated by Django 4.2.5 on 2023-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0009_rename_exist_descendant_is_exist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ascendant',
            old_name='exist',
            new_name='is_exist',
        ),
    ]
