# Generated by Django 4.2.5 on 2023-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0010_rename_exist_ascendant_is_exist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='exist',
        ),
        migrations.AddField(
            model_name='collateral',
            name='is_exist',
            field=models.BooleanField(default=False, verbose_name='死亡時存在'),
        ),
    ]
