# Generated by Django 4.2.5 on 2023-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0011_remove_collateral_exist_collateral_is_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascendant',
            name='is_exist',
            field=models.BooleanField(null=True, verbose_name='死亡時存在'),
        ),
        migrations.AlterField(
            model_name='ascendant',
            name='is_japan',
            field=models.BooleanField(null=True, verbose_name='日本在住'),
        ),
        migrations.AlterField(
            model_name='ascendant',
            name='is_live',
            field=models.BooleanField(null=True, verbose_name='手続時存在'),
        ),
        migrations.AlterField(
            model_name='ascendant',
            name='is_refuse',
            field=models.BooleanField(null=True, verbose_name='相続放棄'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='is_adult',
            field=models.BooleanField(null=True, verbose_name='成人'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='is_exist',
            field=models.BooleanField(null=True, verbose_name='死亡時存在'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='is_japan',
            field=models.BooleanField(null=True, verbose_name='日本在住'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='is_live',
            field=models.BooleanField(null=True, verbose_name='手続時存在'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='is_refuse',
            field=models.BooleanField(null=True, verbose_name='相続放棄'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='is_adult',
            field=models.BooleanField(null=True, verbose_name='成人'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='is_exist',
            field=models.BooleanField(null=True, verbose_name='死亡時存在'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='is_japan',
            field=models.BooleanField(null=True, verbose_name='日本在住'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='is_live',
            field=models.BooleanField(null=True, verbose_name='手続時存在'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='is_refuse',
            field=models.BooleanField(null=True, verbose_name='相続放棄'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='is_exist',
            field=models.BooleanField(null=True, verbose_name='死亡時存在'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='is_japan',
            field=models.BooleanField(null=True, verbose_name='日本在住'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='is_live',
            field=models.BooleanField(null=True, verbose_name='手続時存在'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='is_refuse',
            field=models.BooleanField(null=True, verbose_name='相続放棄'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='氏名'),
        ),
    ]
