# Generated by Django 4.2.5 on 2023-12-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toukiApp', '0012_alter_ascendant_is_exist_alter_ascendant_is_japan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='content_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collateral2', to='contenttypes.contenttype', verbose_name='親2'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='object_id2',
            field=models.PositiveIntegerField(null=True, verbose_name='親2id'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='content_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendant2', to='contenttypes.contenttype', verbose_name='親2'),
        ),
        migrations.AlterField(
            model_name='descendant',
            name='object_id2',
            field=models.PositiveIntegerField(null=True, verbose_name='親2id'),
        ),
    ]
