# Generated by Django 4.2.5 on 2024-01-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0019_alter_ascendant_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decedent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decedent', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
