# Generated by Django 4.2.5 on 2024-01-20 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toukiApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0020_alter_decedent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='decedent',
            name='progress',
            field=models.IntegerField(default=1, verbose_name='進捗'),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('file', models.FileField(upload_to='registers/', validators=[toukiApp.models.validate_file], verbose_name='ファイル')),
                ('file_size', models.IntegerField(verbose_name='サイズ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('decedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='toukiApp.decedent', verbose_name='被相続人')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '不動産登記簿',
                'verbose_name_plural': '不動産登記簿',
            },
        ),
    ]
