# Generated by Django 4.2.5 on 2024-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0021_decedent_progress_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='file',
        ),
        migrations.AddField(
            model_name='register',
            name='extension',
            field=models.CharField(default='pdf', max_length=100, verbose_name='拡張子'),
        ),
        migrations.AddField(
            model_name='register',
            name='path',
            field=models.CharField(default='', max_length=100, verbose_name='パス'),
        ),
        migrations.AlterField(
            model_name='register',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='タイトル'),
        ),
    ]
