# Generated by Django 4.2.5 on 2024-01-31 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0023_decedent_type_of_division_site_relatedindividual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decedent',
            name='address',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='住所の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='bldg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='住所の建物'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='domicile_address',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='本籍地の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='進捗'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='resistry_address',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='登記上の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='resistry_bldg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='登記上の建物'),
        ),
    ]
