# Generated by Django 4.2.5 on 2024-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0024_alter_decedent_address_alter_decedent_bldg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decedent',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='bldg',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所の建物'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='住所の市区町村'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='domicile_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='本籍地の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='domicile_city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='本籍地の市区町村'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='resistry_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='登記上の町域・番地'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='resistry_bldg',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='登記上の建物'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='resistry_city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='登記上の市区町村'),
        ),
    ]
