# Generated by Django 4.2.5 on 2024-02-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toukiApp', '0028_numberofproperties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberofproperties',
            options={'verbose_name': '不動産の数', 'verbose_name_plural': '不動産の数'},
        ),
        migrations.AddField(
            model_name='house',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='相続人'),
        ),
        migrations.AddField(
            model_name='house',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='相続人id'),
        ),
        migrations.AddField(
            model_name='land',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='相続人'),
        ),
        migrations.AddField(
            model_name='land',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='相続人id'),
        ),
    ]
