# Generated by Django 4.2.5 on 2024-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0036_alter_typeofdivision_type_of_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofdivision',
            name='all_cash_Acquirer',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='全金銭の取得者'),
        ),
        migrations.AddField(
            model_name='typeofdivision',
            name='all_property_Acquirer',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='全不動産の取得者'),
        ),
    ]
