# Generated by Django 4.2.5 on 2024-02-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0037_typeofdivision_all_cash_acquirer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofdivision',
            old_name='all_cash_Acquirer',
            new_name='all_cash_acquirer',
        ),
        migrations.RenameField(
            model_name='typeofdivision',
            old_name='all_property_Acquirer',
            new_name='all_property_acquirer',
        ),
    ]
