# Generated by Django 4.2.5 on 2024-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0039_alter_typeofdivision_cash_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofproperties',
            name='bldg',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='区分建物の数'),
        ),
        migrations.AlterField(
            model_name='numberofproperties',
            name='house',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='建物の数'),
        ),
        migrations.AlterField(
            model_name='numberofproperties',
            name='land',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='土地の数'),
        ),
    ]
