# Generated by Django 4.2.5 on 2024-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0041_alter_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_exchange',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='換価対象'),
        ),
        migrations.AddField(
            model_name='land',
            name='is_exchange',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='換価対象'),
        ),
    ]
