# Generated by Django 4.2.5 on 2024-02-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0042_house_is_exchange_land_is_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='家屋番号'),
        ),
        migrations.AddField(
            model_name='land',
            name='land_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地番'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.IntegerField(default=None, verbose_name='固定資産評価額'),
        ),
    ]
