# Generated by Django 4.2.5 on 2024-02-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toukiApp', '0044_alter_house_price_alter_land_price_alter_site_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofdivision',
            name='all_cash_acquirer',
        ),
        migrations.RemoveField(
            model_name='typeofdivision',
            name='all_property_acquirer',
        ),
        migrations.AddField(
            model_name='typeofdivision',
            name='content_type1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_division1', to='contenttypes.contenttype', verbose_name='不動産全取得者'),
        ),
        migrations.AddField(
            model_name='typeofdivision',
            name='content_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_division2', to='contenttypes.contenttype', verbose_name='金銭全取得者'),
        ),
        migrations.AddField(
            model_name='typeofdivision',
            name='object_id1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='不動産全取得者id'),
        ),
        migrations.AddField(
            model_name='typeofdivision',
            name='object_id2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='金銭全取得者id'),
        ),
    ]
