# Generated by Django 4.2.5 on 2024-02-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0045_remove_typeofdivision_all_cash_acquirer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='building',
            new_name='house',
        ),
        migrations.AlterField(
            model_name='typeofdivision',
            name='property_allocation',
            field=models.CharField(blank=True, choices=[('全て法定相続', '全て法定相続'), ('その他', 'その他')], max_length=30, null=True, verbose_name='不動産の分配方法'),
        ),
    ]
