# Generated by Django 4.2.5 on 2024-03-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0047_application_alter_relatedindividual_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationoffice',
            name='name',
        ),
        migrations.AddField(
            model_name='destinationoffice',
            name='main',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='本局'),
        ),
        migrations.AddField(
            model_name='destinationoffice',
            name='sub',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='支局・出張所'),
        ),
        migrations.AddField(
            model_name='destinationoffice',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('支局', '支局'), ('出張所', '出張所')], max_length=10, null=True, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='application',
            name='agent_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='代理人住所'),
        ),
        migrations.AlterField(
            model_name='application',
            name='agent_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='代理人氏名'),
        ),
        migrations.AlterField(
            model_name='application',
            name='agent_phone_number',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='代理人電話番号'),
        ),
        migrations.AlterField(
            model_name='collateralcommon',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='兄弟姉妹の数'),
        ),
        migrations.AlterField(
            model_name='destinationoffice',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='destinationoffice',
            name='code',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='法務局コード'),
        ),
        migrations.AlterField(
            model_name='destinationoffice',
            name='post_number',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='郵便番号'),
        ),
    ]
