# Generated by Django 4.2.5 on 2024-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0048_remove_destinationoffice_name_destinationoffice_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationoffice',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('本局のみ', '本局のみ'), ('支局', '支局'), ('出張所', '出張所')], max_length=10, null=True, verbose_name='種別'),
        ),
    ]
