# Generated by Django 4.2.5 on 2024-03-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0049_alter_destinationoffice_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='office',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='法務局'),
        ),
        migrations.AddField(
            model_name='land',
            name='office',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='法務局'),
        ),
        migrations.DeleteModel(
            name='DestinationOffice',
        ),
    ]
