# Generated by Django 4.2.5 on 2024-03-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0050_house_office_land_office_delete_destinationoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('code', models.CharField(default='', max_length=4, verbose_name='コード')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '法務局',
                'verbose_name_plural': '法務局',
            },
        ),
    ]
