# Generated by Django 4.2.5 on 2024-03-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0051_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='name',
            new_name='office_name',
        ),
    ]
