# Generated by Django 4.2.5 on 2024-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0052_rename_name_office_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinquiry',
            name='subject',
            field=models.CharField(choices=[('サポート内容', 'サポート内容'), ('料金', '料金'), ('オプション', 'オプション'), ('提携司法書士', '提携司法書士'), ('運営者', '運営者'), ('その他', 'その他')], max_length=20, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='site',
            name='land_type',
            field=models.CharField(blank=True, choices=[('所有権', '所有権'), ('地上権', '地上権'), ('賃借権', '賃借権')], max_length=30, null=True, verbose_name='敷地権の種類'),
        ),
    ]
