# Generated by Django 4.2.5 on 2024-03-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0054_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_register', to='toukiApp.registrynameandaddress', verbose_name='不動産登記簿'),
        ),
    ]
