# Generated by Django 4.2.5 on 2024-03-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0055_alter_land_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='house',
        ),
        migrations.RemoveField(
            model_name='site',
            name='land_num',
        ),
        migrations.RemoveField(
            model_name='site',
            name='land_purparty',
        ),
        migrations.RemoveField(
            model_name='site',
            name='land_type',
        ),
        migrations.AddField(
            model_name='site',
            name='address_and_land_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='所在及び地番'),
        ),
        migrations.AddField(
            model_name='site',
            name='number',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='土地の符号'),
        ),
        migrations.AddField(
            model_name='site',
            name='purparty_bottom',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='敷地権の割合（分母）'),
        ),
        migrations.AddField(
            model_name='site',
            name='purparty_top',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='敷地権の割合（分子）'),
        ),
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.CharField(blank=True, choices=[('所有権', '所有権'), ('地上権', '地上権'), ('賃借権', '賃借権')], max_length=3, null=True, verbose_name='敷地権の種類'),
        ),
        migrations.AlterField(
            model_name='house',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_register', to='toukiApp.registrynameandaddress', verbose_name='不動産登記簿'),
        ),
        migrations.CreateModel(
            name='Bldg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('number', models.CharField(default='', max_length=100, verbose_name='不動産番号')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='一棟の建物の所在')),
                ('bldg_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='家屋番号')),
                ('purpose', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='種類')),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='構造')),
                ('first_floor_size', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='１階面積')),
                ('second_floor_size', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='２階面積')),
                ('third_floor_size', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='３階面積')),
                ('fourth_floor_size', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='４階面積')),
                ('fifth_floor_size', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='５階面積')),
                ('purparty', models.CharField(default='', max_length=100, verbose_name='所有権・持分')),
                ('price', models.CharField(default='', max_length=13, verbose_name='固定資産評価額')),
                ('is_exchange', models.BooleanField(blank=True, default=None, null=True, verbose_name='換価対象')),
                ('office', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='法務局')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bldg_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('decedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bldgs', to='toukiApp.decedent', verbose_name='被相続人')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bldg_register', to='toukiApp.registrynameandaddress', verbose_name='不動産登記簿')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bldg_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '区分建物',
                'verbose_name_plural': '区分建物',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='bldg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_bldg', to='toukiApp.bldg', verbose_name='区分建物'),
        ),
    ]
