# Generated by Django 4.2.5 on 2024-03-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0056_remove_site_house_remove_site_land_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrynameandaddress',
            options={'verbose_name': '登記簿上の住所氏名', 'verbose_name_plural': '登記簿上の住所氏名'},
        ),
    ]
