# Generated by Django 4.2.5 on 2024-03-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0057_alter_registrynameandaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bldg',
            name='price',
            field=models.CharField(default='', max_length=16, verbose_name='固定資産評価額'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(default='', max_length=16, verbose_name='固定資産評価額'),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.CharField(default='', max_length=16, verbose_name='固定資産評価額'),
        ),
        migrations.AlterField(
            model_name='site',
            name='price',
            field=models.CharField(default='', max_length=16, verbose_name='固定資産評価額'),
        ),
    ]
