# Generated by Django 4.2.5 on 2024-03-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0058_alter_bldg_price_alter_house_price_alter_land_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bldg',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bldg_register', to='toukiApp.register', verbose_name='不動産登記簿'),
        ),
        migrations.AlterField(
            model_name='house',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_register', to='toukiApp.register', verbose_name='不動産登記簿'),
        ),
        migrations.AlterField(
            model_name='land',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_register', to='toukiApp.register', verbose_name='不動産登記簿'),
        ),
    ]
