# Generated by Django 4.2.5 on 2024-04-09 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0060_alter_openinquiry_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('category', models.CharField(choices=[('基本データ入力', '基本データ入力'), ('必要書類一覧', '必要書類一覧'), ('詳細データ入力', '詳細データ入力'), ('書類の印刷', '書類の印刷'), ('法務局に申請', '法務局に申請'), ('申請後について', '申請後について')], max_length=50, verbose_name='進捗状況')),
                ('subject', models.CharField(choices=[('お亡くなりになった方（被相続人）について', 'お亡くなりになった方（被相続人）について'), ('配偶者について', '配偶者について'), ('子供全員について', '子供全員について'), ('各子について', '各子について'), ('子の配偶者について', '子の配偶者について'), ('孫について', '孫について'), ('父について', '父について'), ('母について', '母について'), ('父方の祖父について', '父方の祖父について'), ('父方の祖母について', '父方の祖母について'), ('母方の祖父について', '母方の祖父について'), ('母方の祖母について', '母方の祖母について'), ('兄弟姉妹全員について', '兄弟姉妹全員について'), ('各兄弟姉妹について', '各兄弟姉妹について'), ('その他', 'その他'), ('亡くなった方の出生から死亡までの戸籍謄本', '亡くなった方の出生から死亡までの戸籍謄本'), ('被相続人の住民票の除票又は戸籍の附票', '被相続人の住民票の除票又は戸籍の附票'), ('固定資産評価証明書', '固定資産評価証明書'), ('登記簿謄本', '登記簿謄本'), ('不動産を取得する方の住民票又は戸籍の附票', '不動産を取得する方の住民票又は戸籍の附票'), ('全相続人の印鑑証明書', '全相続人の印鑑証明書'), ('全相続人の全部事項証明書', '全相続人の全部事項証明書'), ('その他', 'その他'), ('被相続人情報', '被相続人情報'), ('相続人情報', '相続人情報'), ('遺産分割方法', '遺産分割方法'), ('土地情報', '土地情報'), ('建物情報', '建物情報'), ('区分建物情報', '区分建物情報'), ('申請情報', '申請情報'), ('その他', 'その他'), ('遺産分割協議証明書', '遺産分割協議証明書'), ('委任状', '委任状'), ('登記申請書', '登記申請書'), ('相続関係説明図', '相続関係説明図'), ('その他', 'その他'), ('取得した書類を確認する', '取得した書類を確認する'), ('下記書類を登記申請書（申請書）と同じ通数コピーする', '下記書類を登記申請書（申請書）と同じ通数コピーする'), ('下記の順番で書類を全て重ねて左側2か所をホッチキスで留めする', '下記の順番で書類を全て重ねて左側2か所をホッチキスで留めする'), ('３でホッチキス留めした書類に記入押印等する', '３でホッチキス留めした書類に記入押印等する'), ('４まで処理した書類の後ろに書類の原本を以下の順番で重ねてクリアファイルにはさむ', '４まで処理した書類の後ろに書類の原本を以下の順番で重ねてクリアファイルにはさむ'), ('法務局に書類を提出する', '法務局に書類を提出する'), ('その他', 'その他'), ('提出した申請書類に不備があった場合', '提出した申請書類に不備があった場合'), ('手続が完了したら', '手続が完了したら'), ('その他', 'その他')], max_length=50, verbose_name='項目')),
                ('content', models.TextField(max_length=300, verbose_name='質問')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inquiry_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inquiry_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inquiry', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーのお問い合わせ',
                'verbose_name_plural': 'ユーザーのお問い合わせ',
            },
        ),
        migrations.CreateModel(
            name='AnswerToUserInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('content', models.TextField(max_length=300, verbose_name='回答')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_user_inquiry_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_user_inquiry', to='toukiApp.userinquiry', verbose_name='ユーザーのお問い合わせ')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_user_inquiry_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'ユーザーのお問い合わせに対する回答',
                'verbose_name_plural': 'ユーザーのお問い合わせに対する回答',
            },
        ),
    ]
