# Generated by Django 4.2.5 on 2024-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0063_alter_userinquiry_category_alter_userinquiry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='category',
            field=models.CharField(choices=[('0', '基本データ入力'), ('1', '必要書類一覧'), ('2', '詳細データ入力'), ('3', '書類の印刷'), ('4', '法務局に申請'), ('5', '申請後について')], max_length=50, verbose_name='進捗状況'),
        ),
    ]
