# Generated by Django 4.2.5 on 2024-04-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0064_alter_userinquiry_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answertouserinquiry',
            old_name='inquiry',
            new_name='user_inquiry',
        ),
    ]
