# Generated by Django 4.2.5 on 2024-04-11 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0066_alter_userinquiry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertouserinquiry',
            name='user_inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_user_inquiry', to='toukiApp.userinquiry', verbose_name='ユーザーのお問い合わせ'),
        ),
    ]
