# Generated by Django 4.2.5 on 2024-04-12 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toukiApp', '0067_alter_answertouserinquiry_user_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToOpenInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('content', models.TextField(max_length=300, verbose_name='回答')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_open_inquiry_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('open_inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_open_inquiry', to='toukiApp.openinquiry', verbose_name='一般お問い合わせ')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_open_inquiry_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '一般のお問い合わせに対する回答',
                'verbose_name_plural': '一般のお問い合わせに対する回答',
            },
        ),
    ]
