# Generated by Django 4.2.5 on 2024-04-16 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0068_answertoopeninquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decedent',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='進捗'),
        ),
    ]
