# Generated by Django 4.2.5 on 2024-05-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toukiApp', '0070_alter_userinquiry_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistryNameAndAddress',
        ),
    ]
