databases:
  - name: souzokutoukikun
    region: singapore
    plan: Starter
    databaseName: souzokutoukikun_4fnm
    user: souzokutoukikun

services:
  - type: web
    name: そうぞくとうきくん
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn toukiAi.wsgi:application'
    plan: Starter
    branch: master
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: souzokutoukikun_4fnm
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true