databases:
  - name: toukikun
    region: singapore
    plan: Starter
    databaseName: souzokutoukikun
    user: souzokutoukikun

services:
  - type: web
    name: そうぞくとうきくん
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn toukiAi.wsgi:application'
    plan: Free
    branch: master
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: souzokutoukikun
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true