# Generated by Django 4.2.5 on 2023-09-07 05:21

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agreement',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='お名前'),
        ),
    ]
