# Generated by Django 4.2.5 on 2023-09-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.CharField(choices=[(0, '振込'), (1, 'カード')], default=1, max_length=30, verbose_name='支払方法'),
        ),
        migrations.AlterField(
            model_name='user',
            name='progress',
            field=models.CharField(choices=[(0, 'step1'), (1, 'step2'), (2, 'step3'), (3, 'step4'), (4, 'step5'), (5, 'step6')], default=0, max_length=30, verbose_name='進捗'),
        ),
    ]
