# Generated by Django 4.2.5 on 2023-09-16 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_payment_alter_user_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='変更後のメールアドレス')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmailChange', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メールアドレス変更申請',
                'verbose_name_plural': 'メールアドレス変更申請',
            },
        ),
    ]
