# Generated by Django 4.2.5 on 2024-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option6_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='progress',
        ),
        migrations.AddField(
            model_name='user',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='システムの有料版'),
        ),
        migrations.AddField(
            model_name='user',
            name='basic_date',
            field=models.DateTimeField(null=True, verbose_name='システムの有料版の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option1',
            field=models.BooleanField(default=False, verbose_name='戸籍取得代行の利用状況'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option1_date',
            field=models.DateTimeField(null=True, verbose_name='戸籍取得代行の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option2',
            field=models.BooleanField(default=False, verbose_name='司法書士紹介の利用状況'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option2_date',
            field=models.DateTimeField(null=True, verbose_name='司法書士紹介の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option3_date',
            field=models.DateTimeField(null=True, verbose_name='オプション3の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option4_date',
            field=models.DateTimeField(null=True, verbose_name='オプション4の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option5_date',
            field=models.DateTimeField(null=True, verbose_name='オプション5の利用開始日'),
        ),
    ]
