# Generated by Django 4.2.5 on 2024-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_option6_remove_user_option6_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basic_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='システムの有料版の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option1_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='戸籍取得代行の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option2_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='司法書士紹介の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option3_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='オプション3の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option4_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='オプション4の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option5_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='オプション5の利用開始日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.CharField(blank=True, choices=[('振込', '振込'), ('カード', 'カード')], max_length=30, null=True, verbose_name='支払方法'),
        ),
    ]
