# Generated by Django 4.2.5 on 2024-04-25 09:51

import common.validations
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('is_recieved', models.BooleanField(default=False, verbose_name='着金確認')),
                ('is_recieved_date', models.DateTimeField(blank=True, null=True, verbose_name='着金確認日')),
                ('name', models.CharField(max_length=30, validators=[common.validations.JapaneseOnlyValidator()], verbose_name='氏名')),
                ('payer', models.CharField(max_length=30, validators=[common.validations.validate_katakana], verbose_name='支払名義人')),
                ('address', models.CharField(default='', max_length=100, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='ハイフンなしの10桁又は11桁で入力してください', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_request_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_request_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_request', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'オプション利用申請',
                'verbose_name_plural': 'オプション利用申請',
            },
        ),
    ]
