# Generated by Django 4.2.5 on 2024-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_optionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionrequest',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='システムの有料版'),
        ),
        migrations.AddField(
            model_name='optionrequest',
            name='option1',
            field=models.BooleanField(default=False, verbose_name='戸籍取得代行の利用状況'),
        ),
        migrations.AddField(
            model_name='optionrequest',
            name='option2',
            field=models.BooleanField(default=False, verbose_name='司法書士紹介の利用状況'),
        ),
    ]
