# Generated by Django 4.2.5 on 2024-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_optionrequest_basic_optionrequest_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionrequest',
            name='is_phone_required',
            field=models.BooleanField(default=False, verbose_name='電話による連絡を希望'),
        ),
    ]
