# Generated by Django 4.2.5 on 2024-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_optionrequest_is_phone_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionrequest',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='システムの有料版の申込み'),
        ),
        migrations.AlterField(
            model_name='optionrequest',
            name='option1',
            field=models.BooleanField(default=False, verbose_name='戸籍取得代行の申込み'),
        ),
        migrations.AlterField(
            model_name='optionrequest',
            name='option2',
            field=models.BooleanField(default=False, verbose_name='司法書士紹介の申込み'),
        ),
    ]
