# Generated by Django 4.2.5 on 2024-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_optionrequest_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionrequest',
            name='charge',
            field=models.PositiveIntegerField(default=0, verbose_name='支払額'),
        ),
    ]
