# Generated by Django 4.2.5 on 2024-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_optionrequest_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionrequest',
            name='is_phone_required',
        ),
        migrations.AlterField(
            model_name='optionrequest',
            name='charge',
            field=models.CharField(default='０', max_length=6, verbose_name='支払額'),
        ),
    ]
