# Generated by Django 4.2.5 on 2024-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_optionrequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
