# Generated by Django 4.2.5 on 2024-05-26 13:02

import common.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_optionrequest_access_id_optionrequest_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=11, validators=[common.validations.validate_no_hyphen_phone_number], verbose_name='電話番号'),
        ),
    ]
