# Generated by Django 4.2.5 on 2024-06-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_user_payment_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='optionrequest',
            name='is_recieved',
        ),
        migrations.RemoveField(
            model_name='optionrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='optionrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='option5',
        ),
    ]
