# Generated by Django 4.2.5 on 2024-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_optionrequest_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionrequest',
            old_name='is_recieved_date',
            new_name='recieved_date',
        ),
    ]
