# Generated by Django 4.2.5 on 2024-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_is_recieved_date_optionrequest_recieved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionrequest',
            name='terms_agreement',
            field=models.BooleanField(default=False, verbose_name='規約への同意'),
        ),
    ]
