# Generated by Django 4.2.5 on 2024-06-04 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_optionrequest_terms_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='セッションID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='変更後のメールアドレス')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メールアドレス認証',
                'verbose_name_plural': 'メールアドレス認証',
            },
        ),
    ]
