# Generated by Django 4.2.5 on 2024-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_emailverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='認証結果'),
        ),
    ]
