# Generated by Django 4.2.5 on 2024-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_emailverification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.PositiveIntegerField(verbose_name='トークン'),
        ),
    ]
