# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - toukikun

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get details of installed packages
        run: |
          echo "Getting details of installed packages:"
          for module in $(pip freeze | awk -F== '{print $1}'); do
              echo "Details for $module"
              pip show $module
          done 
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Collect static
        run: python manage.py collectstatic --noinput

      - name: Run tests
        run: python manage.py test
        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4.3.1
        with:
          name: python-app
          path: |
            release.zip
            !venv/
      
      - name: unzip for check
        run: unzip -l release.zip
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_22C637E89D5746F2B49F905C30B0CEAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88ABC828D0CC401AAE42B9E5D7C01899 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_230DFB3784404E878668B2621A256AD8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'toukikun'
          slot-name: 'Production'
          